// apps/landing/components/landing/SiteFooter.vue
<template>
  <footer class="section-dark border-t border-zinc-800 py-16 px-6">
    <div class="max-w-5xl mx-auto grid grid-cols-1 sm:grid-cols-3 gap-12">
      <!-- Branding -->
      <div class="flex flex-col gap-4">
        <span class="text-xl font-bold tracking-tight"> Cr<span class="text-[#ff6b35]">AI</span>te </span>
        <p class="text-sm text-zinc-500 leading-relaxed">
          {{ t('footer.tagline') }}
        </p>
      </div>

      <!-- Product -->
      <div class="flex flex-col gap-3">
        <span class="text-xs font-semibold uppercase tracking-widest text-zinc-400 mb-1">{{
          t('footer.product')
        }}</span>
        <button
          class="text-sm text-zinc-500 hover:text-white transition-colors text-left"
          @click="scrollTo('how-it-works')"
        >
          {{ t('header.howItWorks') }}
        </button>
        <button class="text-sm text-zinc-500 hover:text-white transition-colors text-left" @click="scrollTo('faq')">
          {{ t('header.faq') }}
        </button>
        <button
          class="text-sm text-zinc-500 hover:text-white transition-colors text-left"
          @click="scrollTo('download')"
        >
          {{ t('header.download') }}
        </button>
      </div>

      <!-- Resources -->
      <div class="flex flex-col gap-3">
        <span class="text-xs font-semibold uppercase tracking-widest text-zinc-400 mb-1">
          {{ t('footer.resources') }}
        </span>
        <a
          href="https://github.com/CedricLuccheseDev/Craite"
          target="_blank"
          class="text-sm text-zinc-500 hover:text-white transition-colors"
          >GitHub</a
        >
        <NuxtLink :to="localePath('/privacy')" class="text-sm text-zinc-500 hover:text-white transition-colors">
          {{ t('footer.privacy') }}
        </NuxtLink>
      </div>
    </div>

    <!-- Bottom bar -->
    <div
      class="max-w-5xl mx-auto mt-12 pt-8 border-t border-zinc-800 flex flex-col sm:flex-row items-center justify-between gap-4"
    >
      <p class="text-xs text-zinc-600">{{ t('footer.copyright', { year }) }}</p>
      <div class="flex items-center gap-4">
        <a
          href="https://github.com/CedricLuccheseDev/Craite"
          target="_blank"
          class="text-zinc-600 hover:text-white transition-colors"
        >
          <UIcon name="i-lucide-github" class="text-lg" />
        </a>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
const { t } = useI18n();
const localePath = useLocalePath();
const year = new Date().getFullYear();

function scrollTo(id: string) {
  document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
}
</script>

// apps/landing/src/components/SiteFooter.tsx
import { Wordmark } from './Wordmark'
import { LocaleSwitch } from './LocaleSwitch'
import { REPO } from '~/content/landing'
import { useMessages } from '~/i18n'

export function SiteFooter() {
  const m = useMessages()
  const year = new Date().getFullYear()

  const links = [
    { href: '#how', label: m.nav.how },
    { href: '#faq', label: m.nav.faq },
    { href: '#download', label: m.nav.download },
  ]
  const resources = [
    { href: REPO, label: m.footer.github },
    { href: `${REPO}/issues`, label: m.footer.issues },
    { href: `${REPO}/releases`, label: m.footer.releases },
  ]

  return (
    <footer className="border-t border-hairline">
      <div className="mx-auto grid max-w-5xl gap-10 px-5 py-12 sm:grid-cols-3 sm:px-8">
        <div>
          <Wordmark className="text-lg" />
          <p className="mt-3 max-w-xs text-sm text-pretty text-dim">
            {m.footer.tagline}
          </p>
        </div>

        <FooterColumn title={m.footer.product} items={links} />
        <FooterColumn title={m.footer.resources} items={resources} external />
      </div>

      <div className="mx-auto flex max-w-5xl flex-wrap items-center justify-between gap-2 border-t border-hairline px-5 py-6 sm:px-8">
        <p className="font-mono text-xs text-dim">
          © {year} craite. {m.footer.rights}
        </p>
        <LocaleSwitch className="-mx-2" />
      </div>
    </footer>
  )
}

function FooterColumn({
  title,
  items,
  external = false,
}: {
  title: string
  items: Array<{ href: string; label: string }>
  external?: boolean
}) {
  return (
    <div>
      <p className="type-label">{title}</p>
      <ul className="mt-2">
        {items.map((item) => (
          <li key={item.href}>
            <a
              href={item.href}
              target={external ? '_blank' : undefined}
              rel={external ? 'noreferrer' : undefined}
              className="inline-flex min-h-11 items-center text-sm text-dim transition-colors duration-150 hover:text-ink"
            >
              {item.label}
            </a>
          </li>
        ))}
      </ul>
    </div>
  )
}
